# Generated by Django 5.2.7 on 2025-10-03 20:25

import django.db.models.deletion
import uploads.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(blank=True, max_length=255, null=True)),
                ('filter_type', models.CharField(blank=True, max_length=20, null=True)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=uploads.models.upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('result', models.CharField(choices=[('benign', 'Benign'), ('malignant', 'Malignant'), ('suspicious', 'Suspicious')], max_length=20)),
                ('confidence', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('should_consult_doctor', models.BooleanField(default=False)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('recommendation_message', models.TextField()),
                ('analysis_factors', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'image_uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
