# Generated by Django 5.2.7 on 2025-10-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='cancer_type',
            field=models.CharField(blank=True, choices=[('melanoma', 'Melanoma'), ('basal_cell_carcinoma', 'Basal Cell Carcinoma'), ('squamous_cell_carcinoma', 'Squamous Cell Carcinoma'), ('merkel_cell_carcinoma', 'Merkel Cell Carcinoma'), ('sebaceous_gland_carcinoma', 'Sebaceous Gland Carcinoma'), ('actinic_keratosis', 'Actinic Keratosis'), ('seborrheic_keratosis', 'Seborrheic Keratosis'), ('benign_mole', 'Benign Mole')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='cancer_type_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='cancer_type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='risk_level',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='none', max_length=15),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='urgency_level',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('immediate', 'Immediate')], default='none', max_length=15),
        ),
    ]
